# Generated by Django 5.1.1 on 2024-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studforce_customer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsize",
            name="type_size",
            field=models.CharField(
                choices=[("EUR", "Eur"), ("US", "Us"), ("UK", "Uk"), ("CM", "Cm")],
                default="EUR",
                max_length=10,
            ),
        ),
    ]
