# Generated by Django 5.1.1 on 2024-10-07 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studforce_auth", "0001_initial"),
        (
            "studforce_customer",
            "0003_alter_productimage_product_alter_productsize_product",
        ),
        ("studforce_product", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Administrator",
        ),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="studforce_auth.customer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="studforce_auth.customer",
            ),
        ),
        migrations.AlterField(
            model_name="customeraddress",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="studforce_auth.customer",
                verbose_name="Customer",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.RemoveField(
            model_name="productsize",
            name="product",
        ),
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="studforce_product.product",
            ),
        ),
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.AlterField(
            model_name="productorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="studforce_product.product",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studforce_product.promotion",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                through="studforce_customer.ProductOrder",
                to="studforce_product.product",
            ),
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductSize",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
    ]
