# Generated by Django 5.1.1 on 2024-10-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "studforce_customer",
            "0004_delete_administrator_alter_cart_customer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="size",
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name="cart",
            name="type_size",
            field=models.CharField(default="EUR", max_length=10),
        ),
    ]
