# Generated by Django 5.1.1 on 2024-09-30 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studforce_customer", "0002_alter_productsize_type_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="studforce_customer.product",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="size",
                to="studforce_customer.product",
            ),
        ),
    ]
